[package]
name = "oss-insight-db"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.23"
oss-insight-source = { version = "0.1.0", path = "../oss-insight-source" }
serde_json = "1.0.151"
sqlx = { version = "0.9", features = ["runtime-tokio", "sqlite"] }
thiserror = "2"

[dev-dependencies]
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
